apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# TODO(TEAM-INFRA): Add PodSecurity admission labels

namespace: tm-acme-shop

resources:
  - ../../base

patches:
  - path: patch-tight-security.yaml
    target:
      kind: Deployment
  - path: patch-feature-flags.yaml

commonLabels:
  environment: production

commonAnnotations:
  acme-shop.io/environment: production
